---
- name: This playbook creates a Apache server
  hosts: webservers
  become: true
  tasks:
  - name: Creating Apache server
    yum:
       name: tomcat
       state: present
  - name: starting the Apache services
    service:
        name: tomcat
        state: started
