---
- name: This Playbook uninstall the httpd packages
  hosts: all
  become: true
  tasks:
   - name: stopping the service
     service:
        name: httpd
        state: stopped
     when: ansible_os_family == "RedHat"
   - name: uninstlling the httpd packages
     yum:
       name: httpd
       state: absent
     when: ansible_os_family == "RedHat"
   
   - name: stopping the apache2 service
     service:
       name: apache2
       state: stopped
     when: ansible_os_family == "Debian"
   - name: uninstalling the apache2 
     apt:
       name: apache2
       state: absent
     when: ansible_os_family == "Debian"
