---
- name: This playbook installs httpd  using when
  hosts: all
  become: true
  tasks:
   - name: installing httpd on target servers
     yum:
      name: httpd
      state: installed
     when: ansible_os_family == "RedHat"
     tags:  install apache

   - name: starting the services
     service:
      name: httpd
      state: started
     when: ansible_os_family == "RedHat"
     tags: start apache

   - name: installing httpd on target servers
     apt:
      name: apache2
      state: present
     when: ansible_os_family == "Debian"
     tags: install apache

   - name: starting the services
     service:
        name: apache2
     when: ansible_os_family == "Debian"
     tags: start apache

   - name: copying html file
     copy:
        src:  /opt/ansible/index.html
        dest: /var/www/html
        mode: 0755 
